version: "3"

services:
  mysql:
    container_name: mysql
    image: psyoblade/docker-for-mysql:1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: sqoop
      MYSQL_PASSWORD: sqoop
    ports:
      - '13306:3306'
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
    volumes:
      - ./etc:/etc/mysql/conf.d
      - ./sql:/var/sql
      - ./init:/docker-entrypoint-initdb.d
